### ISSUE TITLE
Request: Add ASN support

### ISSUE THREAD

**Issue by Freeyamacadoya** [replydev/Quboscanner#11]
So you have the ability to scan an iprange, but can you add a feature to be able to use an ASN to gather all it's ipranges? I.E. AS16276 would scan 137.74.0.0/16 135.148.0.0/17 etc. I don't code java or I would do this, it is super helpful ;-;

**Comment by replydev** [comment]
Implement this feature by yourself or ask someone to do that becouse i do not have time. Maybe you just could make a bash script with multiple commands and redirect the outputs to a file.
