### ISSUE TITLE
Add 0.4 to Releases

### ISSUE THREAD

**Issue by ghost** [replydev/Quboscanner#22]
I built version 0.4, but for people who doesn't know how to build, they doesn't know that exist 0.4 version, so can u add to Releases?

**Comment by Vertical2222** [comment]
> I built version 0.4, but for people who doesn't know how to build, they doesn't know that exist 0.4 version, so can u add to Releases?

can you give me it

**Comment by replydev** [comment]
Release 1.0.0 has been released.
