### ISSUE TITLE
old one is better

### ISSUE THREAD

**Issue by krispyking24** [replydev/Quboscanner#28]
ive found the old one (quboscanner-0.3.7-jar-with-dependencies.jar) better as when i searched for a server one the new one (look at the top image) it found no servers but on what looks to be the same settings it found 4 servers(look at the image at the bottom)
![image](https://user-images.githubusercontent.com/77263183/218239972-9fc0df5d-20c1-4df8-8e2f-f0693df5a848.png)
![image](https://user-images.githubusercontent.com/77263183/218239897-a2d7f01d-2170-4e06-a4fd-03fd483d8280.png)

**Comment by replydev** [comment]
Try to increase timeout, it should not slowdown like the previous version but can be more accurate.

**Comment by krispyking24** [comment]
ok will give it a go what timeout would u say is best?

**Comment by replydev** [comment]
> ok will give it a go what timeout would u say is best?

10000 ms could be good for example.

**Comment by krispyking24** [comment]
ok thanks
