### ISSUE TITLE
Qubo doesn't find server with IP range

### ISSUE THREAD

**Issue by Troughy** [replydev/Quboscanner#31]
So when I try to use Qubo with `-i 123.123.123.*`, it doesn't find any servers, but when I give the full ip (for example `-i 123.123.123.69`), it finds the server. I have also read about IP blocks so I tried 123.123.123.0/24 but that didn't seem to work either. The full command: `java -Dfile.encoding=UTF-8 --enable-preview -jar quboscanner-1.0.0-jar-with-dependencies.jar -i x.y.z.* -t 50000 -p 25500-25600`

**Comment by underscore281** [comment]
Same problem here I am having trouble linking multiple range's together too but that is strong possibility of me just not doing it correctly.

**Comment by replydev** [comment]
Networking and IO in general can be unpredictable, and probably this is not a specific issue of this project.

**Comment by underscore281** [comment]
Alright thank you!
