### ISSUE TITLE
What i do wrong

### ISSUE THREAD

**Issue by itsreyi** [replydev/Quboscanner#36]
![image](https://github.com/replydev/Quboscanner/assets/136232606/60cfc413-3da4-452d-932e-eeba210042e6)

im on java 20 

![image](https://github.com/replydev/Quboscanner/assets/136232606/2220fef4-15de-4683-9ca0-d5d0c89dc620)

pls help me

**Comment by replydev** [comment]
I'm sorry but this is not an help desk. The README.md of this repository is clear, use Java 19. Everything is explained clearly and you seem to get annoyed reading it.

From now, any others useless issues from you will be closed with no further response.
