### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by zHadsaw** [replydev/Quboscanner#4]
The Button "Old Threading" close the program.
And ip's of servers with not allow connections do not accept connection except by tcp-shield, him not can pull. But the mcsrvstat can.
Look:
https://mcsrvstat.us/server/51.81.56.60:25565
51.81.56.60:25565
And add a button what generates one "servers.dat" just like minecraft in .minecraft %appdata% folder.

**Comment by replydev** [comment]
Thanks, i will try to fix old threading, and implement servers.dat generation, but i cannot assure you that i can find a workaround for the second issue.
