### ISSUE TITLE
Java 8+, finds no servers

### ISSUE THREAD

**Issue by Corrected276** [replydev/Quboscanner#8]
So I know there are at least 1 server on the range I used who has the port 25565 for a mc server. You can't join it, but it gives info back in the mc client. The host in question I am scanning for (to test) is a TCP-Shield. Settings are this: 
Range: 51.161.99.*
Port range: 25560-25570
Threads: 500
Timeout: 15000
Motd: EMPTY
Version: 1.8.9
MinPlayers: 0 

checking wireshark, it sends packets out but none of the servers reply.

**Comment by MisterToasty** [comment]
make the version one empty to show tcpshield servers.
