### ISSUE TITLE
its not working

### ISSUE THREAD

**Issue by internet553** [replydev/Quboscanner#9]
when i open the program and fill all   the things when i start is it just shows nothing

**Comment by Freeyamacadoya** [comment]
what IP Range are you scanning? How many threads? What cpu do you have? It takes a while if you have bad CPU/bad internet, low threads, or a large iprange (such as 51.0.0.0/8)

**Comment by limonmavis** [comment]
> what IP Range are you scanning? How many threads? What cpu do you have? It takes a while if you have bad CPU/bad internet, low threads, or a large iprange (such as 51.0.0.0/8)

its not working for me either, it shows nothing

**Comment by replydev** [comment]
I will not reply any issue without any information about your system, your quboscanner version and the settings you used.
